name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create build directory
        run: mkdir -p build
      
      - name: Change to build directory
        run: cd build
      
      - name: Configure project
        run: cmake ..
      
      - name: Build project
        run: make all
