name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install build-essential cmake

      - name: Create build directory
        run: mkdir -p build

      - name: Configure project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build

      # Opcional: Ejecuta pruebas si las tienes
      - name: Run tests
        working-directory: build
        run: ctest
